# Generated by Django 2.2.2 on 2019-06-13 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0002_auto_20190613_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='slug',
            field=models.SlugField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
