# Generated by Django 2.2.2 on 2019-06-23 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0004_auto_20190615_0738'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='profile_picture',
            field=models.ImageField(default=1, help_text='a nice image of you', upload_to='pic_folder/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proposal',
            name='audience',
            field=models.CharField(choices=[('B', 'Beginners'), ('I', 'Intermediate'), ('A', 'Advanced'), ('E', 'Everybody')], default='E', help_text='Who are your target audience?', max_length=2),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='pre_requesite',
            field=models.TextField(blank=True, help_text='what are the pre-requisites for this talk?', null=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='website',
            field=models.URLField(blank=True, help_text='have a link to your personal website/blog?', null=True),
        ),
    ]
