version: '3.7'

services:
  web:
    build: ./web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./web/:/usr/src/web/
    expose:
      - 8000
    environment:
      - DEBUG=1
      - SECRET_KEY=devk33s
      - SQL_ENGINE=django.db.backends.postgresql
      - SQL_DATABASE=pyconng_dev
      - SQL_USER=pyconng
      - SQL_PASSWORD=pyconng
      - SQL_HOST=db
      - SQL_PORT=5432
      - DATABASE=postgres
    depends_on:
      - db
    links:
      - db:db

  db:
    image: postgres:10.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=pyconng
      - POSTGRES_PASSWORD=pyconng
      - POSTGRES_DB=pyconng_dev

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/usr/src/web/staticfiles
    ports:
      - 80:80
    depends_on: 
      - web

volumes:
  postgres_data:
  static_volume: