# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-06-12 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0003_auto_20160322_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talkproposal',
            name='audience_level',
            field=models.IntegerField(choices=[(1, 'Novice'), (3, 'Intermediate or Advanced'), (4, 'Not Applicable')]),
        ),
        migrations.AlterField(
            model_name='tutorialproposal',
            name='audience_level',
            field=models.IntegerField(choices=[(1, 'Novice'), (3, 'Intermediate or Advanced'), (4, 'Not Applicable')]),
        ),
    ]
