# Generated by Django 2.2.2 on 2019-07-04 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketpurchase',
            name='payment_ref',
            field=models.CharField(default='SOME STRING', max_length=50),
        ),
    ]
