# Generated by Django 2.2.2 on 2019-07-05 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticketpurchase_payment_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketpurchase',
            name='payment_ref',
            field=models.CharField(max_length=50),
        ),
    ]
