"""
Django settings for pycon project.

Generated by 'django-admin startproject' using Django 1.11.8.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os
import datetime
import pytz


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATIC_URL = '/static/'

# Extra places for collectstatic to find static files.
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '%%tqgblfsn25q%#47oempdcw8zjoit3hll^p8gbl@#!#4%_6kn'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

DJANGO_APPS = (
    # Default Django apps:
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.sites",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Useful template tags:
    "django.contrib.humanize",
    # Admin
    "django.contrib.admin",
)
THIRD_PARTY_APPS = (
    "crispy_forms",  # Form layouts
    "account",  # registration
    "easy_thumbnails",
    # "taggit",
    "reversion",
    # "metron",
    "sitetree",
    "waffle",
    "markitup",
    "import_export",
    # pinax
    "pinax.boxes",
    # "pinax.eventlog",
    "pinax.pages",
    "pinax.blog",
    "pinax.images",
    # symposion
    "symposion",
    "symposion.conference",
    "symposion.speakers",
    "symposion.proposals",
    "symposion.reviews",
    "symposion.schedule",
    "symposion.sponsorship",
    "symposion.teams",
    "hijack",
    "compat",
    "hijack_admin",
    # 'captcha',
)

# Apps specific for this project go here.
LOCAL_APPS = (
    # custom users app
    "proposals",
    "core",
    # Your stuff: custom apps go here
    "tickets",
)

# See: https://docs.djangoproject.com/en/dev/ref/settings/#installed-apps
INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + LOCAL_APPS

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Simplified static file serving.
    # https://warehouse.python.org/project/whitenoise/
    'whitenoise.middleware.WhiteNoiseMiddleware',
]

ROOT_URLCONF = 'pycon.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR + '/templates/',],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'pycon.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'

##################################################################################
def env(name, default):
    return default


MARKITUP_SET = "markitup/sets/markdown"
MARKITUP_FILTER = ["symposion.markdown_parser.parse", {}]
MARKITUP_SKIN = "markitup/skins/simple"

ACCOUNT_EMAIL_AUTHENTICATION = False
ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS = 2
ACCOUNT_EMAIL_CONFIRMATION_REQUIRED = False
ACCOUNT_EMAIL_VERIFICATION = False
ACCOUNT_LOGIN_URL = LOGIN_URL = "/account/login/"
ACCOUNT_LOGIN_REDIRECT_URL = "dashboard"
ACCOUNT_LOGOUT_REDIRECT_URL = "home"
ACCOUNT_OPEN_SIGNUP = True
ACCOUNT_SIGNUP_REDIRECT_URL = "dashboard"
ACCOUNT_UNIQUE_EMAIL = EMAIL_CONFIRMATION_UNIQUE_EMAIL = False
ACCOUNT_USE_AUTH_AUTHENTICATE = True


def ACCOUNT_USER_DISPLAY(user):
    return user.email


# Symposion settings

CONFERENCE_ID = 1
PROPOSAL_FORMS = {
    "tutorial": "python_nigeria.proposals.forms.TutorialProposalForm",
    "talk-25-min": "python_nigeria.proposals.forms.TalkProposalForm",
    "pydata": "python_nigeria.proposals.forms.TalkProposalForm",
    "talk-45-min": "python_nigeria.proposals.forms.TalkProposalForm",
    "open-space": "python_nigeria.proposals.forms.OpenSpaceProposalForm",
}
# Location of root django.contrib.admin URL, use {% url 'admin:index' %}
ADMIN_URL = r"^admin/"

# Your common stuff: Below this line define 3rd party library settings
# ------------------------------------------------------------------------------

PINAX_PAGES_HOOKSET = "config.hooks.PinaxPagesHookSet"
PINAX_BOXES_HOOKSET = "config.hooks.PinaxBoxesHookSet"

# adjust for number of reviews currenly about 1/5 (default: 3)
SYMPOSION_VOTE_THRESHOLD = 6

MARKITUP_SET = "markitup/sets/markdown"
MARKITUP_FILTER = ["symposion.markdown_parser.parse", {}]
MARKITUP_SKIN = "markitup/skins/simple"

THEME_CONTACT_EMAIL = "hello@pycon.us"
PAYSTACK_BASE_URL = "https://api.paystack.co"
PAYSTACK_SECRET_KEY = env(
    "PAYSTACK_SECRET_KEY", default="sk_test_a551e347b4fc7af40b897f1fc217ce3642d1faa7"
)
PAYSTACK_PUBLIC_KEY = env(
    "PAYSTACK_PUBLIC_KEY", default="pk_test_fbc2f1812af67479da1306edc72890e0702f052e"
)

HIJACK_LOGIN_REDIRECT_URL = (
    "/dashboard/"
)  # Where admins are redirected to after hijacking a user
HIJACK_LOGOUT_REDIRECT_URL = (
    "/we-are-allowed/auth/user/"
)  # Where admins are redirected to after releasing a user
HIJACK_ALLOW_GET_REQUESTS = True

RECAPTCHA_PUBLIC_KEY = env(
    "RECAPTCHA_PUBLIC_KEY", default="6LcXCVAUAAAAAJ91TSqGxTa3klWZkVczL_guXHMN"
)
RECAPTCHA_PRIVATE_KEY = env(
    "RECAPTCHA_PRIVATE_KEY", default="6LcXCVAUAAAAAFOQeqopAJH6_MSPGzMGmnnQUM3G"
)

DEADLINE_DATE = datetime.datetime(2019, 7, 17, 9, tzinfo=pytz.UTC)


PINAX_PAGES_HOOKSET = "pycon.hooks.PinaxPagesHookSet"
PINAX_BOXES_HOOKSET = "pycon.hooks.PinaxBoxesHookSet"

# MEDIA CONFIGURATION
# ------------------------------------------------------------------------------
# See: https://docs.djangoproject.com/en/dev/ref/settings/#media-root
MEDIA_ROOT = "/media/"

# See: https://docs.djangoproject.com/en/dev/ref/settings/#media-url
MEDIA_URL = "/media/"

# TEMPLATE_DIRS = (
#     BASE_DIR + '/templates/',
# )


STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
    '/var/www/static/',
]